In [1]:
import pixiedust
import pyspark
import random
from datetime import datetime
from pyspark.sql.functions import col, udf
from pyspark.sql.types import Row
from pyspark.sql.types import DateType
from sklearn.cluster import DBSCAN
import numpy as np 
from datetime import datetime
import pandas as pd

# Import `pyplot` 
import matplotlib.pyplot as plt

# Set the style to `ggplot`
plt.style.use("ggplot")
pixiedust.enableJobMonitor()

conf = SparkConf().setAppName("App")
conf = (conf.setMaster('local[*]')
        .set('spark.executor.memory', '4G')
        .set('spark.driver.memory', '30G')
        .set('spark.driver.maxResultSize', '10G'))

sc = SparkContext.getOrCreate(conf=conf)
sqlContext = SQLContext(sc)

Pixiedust database opened successfully

Successfully enabled Spark Job Progress Monitor

In [7]:
path='../../../datascience/data/urbs-dbscan/'

toDateTime =  udf(lambda x: datetime.strptime(x, '%d/%m/%Y %H:%M:%S'), DateType())

clusters_df = sqlContext.read.option("header", "true").csv(path+'*.csv',sep=';')
clusters_df = clusters_df.withColumn("data", toDateTime(col('dthr')))

In [8]:
display(clusters_df)

In [9]:
bunching_groups = clusters_df.filter("data < '2018-11-24'").select("cluster_id","cod_linha","key","veic","data") \
.distinct().groupby(["data","cod_linha","key","cluster_id"]) \
.count().sort(col("data").asc(),col("cod_linha"),col("key"),col("cluster_id").asc()).where("count > 1")

In [10]:
display(bunching_groups)

In [13]:
count_occurrences = bunching_groups.groupby(["data","cod_linha"]).count().sort(col("count").desc())